### PR TITLE
Wrfses 151 create endpoints for data retrieval

### PR DESCRIPTION
**Pull request by mikecokingtin**
Get endpoints

---
This change is [Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)

### CODE REVIEW

**Review by apersingerzaius — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @mikecokingtin and @persinac)

___
*[src/app.ts, line 16 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-LfXBywg8yZvO9uI9LXx:-LfXBywg8yZvO9uI9LXy:bk6i27x) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/app.ts#L16)):*
> ```XML
>     public app: express.Application;
>     public routePrv: Routes = new Routes();
>     public catcall: Catcalls = new Catcalls();
> ```

Let's only have one entry point for routes per table? Or maybe we'll have one entry point period (routes.ts) and then extend those classes.

**Review by apersingerzaius — COMMENTED** [review]
Mainly formatting. I'll be working on extending the classes for scalability and manageability. I'm also going to install what's called a 'linter', which is basically a format cop that smacks our wrist every time we don't format something correctly. Helps keep the code consistent and easy to read.

> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4#-:-Lfl6ZDI3hmChrNG4VlC:b6e65qk)* status: 2 of 11 files reviewed, 8 unresolved discussions (waiting on @mikecokingtin and @persinac)

___
*[src/entity/UserAccounts.ts, line 12 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl5BtIDEan_avdjgha:-Lfl5BtIDEan_avdjghb:b-nzn629) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/entity/UserAccounts.ts#L12)):*
> ```XML
>     role_text: string;
> 
> }
> ```

This is on me, but we need to add new lines after the very last line in each file.
___
*[src/routes/catcalls.ts, line 10 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl5Lhu-OyHiu21-eD_:-Lfl5Lhu-OyHiu21-eDa:bys72y6) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/catcalls.ts#L10)):*
> ```XML
> export class Catcalls {
>     public catcalls(app): void {
>         createConnection().then(connection => {
> ```

One of the main reasons we want to attempt to extend the `routes` class is because of this line right here. We don't want to create a new connection with each call to the API per route. Ideally we only create a single connection and use that connection to the repo. This also ensures data integrity and consistency when writing and updating the state on the front end. 
___
*[src/routes/getDetailsById.ts, line 13 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl5dj6Albgr-UGF5tu:-Lfl5dj6Albgr-UGF5tv:bijhnui) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/getDetailsById.ts#L13)):*
> ```XML
> 
>             const repository = connection.getRepository(product_details)
>             app.route('/productDetails/:detailId')
> ```

Routes need to be discussed, but since these will be forward facing, we need to create the routes to act a little more like the user expects.

I suggest we follow this paradigm for endpoints:
`/product/details/:detailId`
`/question/option/:id`
`/user/account`

So basically: `/base/next-step/next-step/.... ` etc.
___
*[src/routes/getDetailsById.ts, line 20 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl6H0W5sSaC3Tzn1Cz:-Lfl6H0W5sSaC3Tzn1D-:bimugsg) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/getDetailsById.ts#L20)):*
> ```XML
>                         .where({
>                             pd_id: req.params.detailId
>                         }
> ```

Formatting please
___
*[src/routes/productDetailsRoutes.ts, line 17 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl6QO1D8tdMC0U78Da:-Lfl6QO1D8tdMC0U78Db:bcqsg2f) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/productDetailsRoutes.ts#L17)):*
> ```XML
>                         }
>                     )
>             }
> ```

Formatting? Wide open space between lines here
___
*[src/routes/qoptionRoutes.ts, line 19 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl6Rsq35xPWCPn5h8p:-Lfl6Rsq35xPWCPn5h8q:bwnzxmw) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/qoptionRoutes.ts#L19)):*
> ```XML
>             }
> 
>         )
> ```

Formatting. Wide open space between lines here
___
*[src/routes/questionRoutes.ts, line 17 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl6Td725DcVgCzvxA2:-Lfl6Td725DcVgCzvxA3:beunyw8) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/questionRoutes.ts#L17)):*
> ```XML
>                 })
> 
>         })
> ```

This formatting is different than the 2 classes above.

**Review by apersingerzaius — COMMENTED** [review]
@mikecokingtin Make sure to change the commit message if you're pushing a bunch of changes.

> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4#-:-LflX18CDjdzLvMMNvpo:b68zt2f)* status: 0 of 21 files reviewed, 11 unresolved discussions (waiting on @apersingerzaius, @mikecokingtin, and @persinac)

___
*[src/app.ts, line 37 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-LflXCl766toXc0wMXP-:-LflXCl766toXc0wMXP0:b-kzdreh) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/app.ts#L37)):*
> ```XML
> 
>     private productDetailsTwo: ProductDetails;
>     private productHeader: ProductHeaders;
> ```

@mikecokingtin I want you to look at how I implemented these classes `ProductDetails.ts`, `ProductHeaders.ts`, and `OurTesterClass.ts`, and see below for how I wrapped the connection around those classes in the app constructor. 
___
*[src/routes/OurTesterClass.ts, line 10 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-LflXlrJ2aOHUaLscReP:-LflXlrJ2aOHUaLscReQ:b-s9j5l0) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/routes/OurTesterClass.ts#L10)):*
> ```XML
> export class OurTesterClass extends Routes {
> 
>   readonly endpoints: Endpoints[];
> ```

@mikecokingtin This is how we'll manage endpoints. See the associated `setEndpoints()` function.
___
*[src/routes/OurTesterClass.ts, line 14 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-LflXtG04MxxKyN1yCup:-LflXtG04MxxKyN1yCuq:bxk9ss3) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/routes/OurTesterClass.ts#L14)):*
> ```XML
>   private repo: Repository<product_header>;
> 
>   constructor(app: Application, conn: Connection) {
> ```

Each class will take in the application and the connection. Thus making them singletons (or at least that's the hope) per session. In each constructor, we'll have to set endpoints, grab the repo the class is associated to, and finally register routes.

**Review by apersingerzaius — COMMENTED** [review]
In general, let's name our files `PascalCase` and our class names follow that nomenclature (ie: `ProductHeader.ts` => `ProductHeader`). Also, no need to append `route` to the file/class names since they already live in the `/routes` directory. It's unnecessarily redundant.

> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4#-:-LflYdBm3MbZ39lCn_vs:bxr2il8)* status: 0 of 21 files reviewed, 12 unresolved discussions (waiting on @apersingerzaius, @mikecokingtin, and @persinac)

___
*[src/routes/hardwareReferenceRoutes.ts, line 15 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-LflYOlJExsa8hq1nu2f:-LflYOlJExsa8hq1nu2g:bb8salj) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/routes/hardwareReferenceRoutes.ts#L15)):*
> ```XML
>                 app.route('/hardwareReference')
>                     .get(async (req: Request, res: Response) => {
>                         const phs = await repository
> ```

Please rename `phs` to something related the class.

**Review by persinac — COMMENTED** [review]
Scratch part of the above comment. We are going to need to append `Route` to our class names for routes since we can't have the same route class name as the entity itself.

> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4#-:-LfowX8Q9cMVSljmSy9X:b-966pdq)* status: 0 of 21 files reviewed, 12 unresolved discussions (waiting on @apersingerzaius, @mikecokingtin, and @persinac)

**Review by persinac — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 4 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: 6 of 21 files reviewed, 12 unresolved discussions (waiting on @apersingerzaius, @mikecokingtin, and @persinac)

___
*[src/entity/UserAccounts.ts, line 12 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl5BtIDEan_avdjgha:-LfowlqI5YqifHVMrv8v:b-ii4qor) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/entity/UserAccounts.ts#L12)):*
<details><summary><i>Previously, apersingerzaius (Alex Persinger) wrote…</i></summary><blockquote>

This is on me, but we need to add new lines after the very last line in each file.
</blockquote></details>

Linter will automatically fix this.

**Review by persinac — COMMENTED** [review]
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: 7 of 21 files reviewed, 12 unresolved discussions (waiting on @apersingerzaius, @mikecokingtin, and @persinac)

**Review by persinac — COMMENTED** [review]
> Dismissed @apersingerzaius from 12 discussions.
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: 7 of 21 files reviewed, 1 unresolved discussion (waiting on @apersingerzaius and @mikecokingtin)

**Review by apersingerzaius — COMMENTED** [review]
> Reviewed 8 of 14 files at r2, 8 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mikecokingtin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: all files reviewed, 3 unresolved discussions

___
*[src/app.ts, line 37 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-LflXCl766toXc0wMXP-:-Lh2ol0w5lxeG6OSUkEG:b-bhiuyd) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/app.ts#L37)):*
<details><summary><i>Previously, apersingerzaius (Alex Persinger) wrote…</i></summary><blockquote>

@mikecokingtin I want you to look at how I implemented these classes `ProductDetails.ts`, `ProductHeaders.ts`, and `OurTesterClass.ts`, and see below for how I wrapped the connection around those classes in the app constructor. 
</blockquote></details>

I'll work on this. Need to decompose how first, but should be doable
___
*[src/routes/catcalls.ts, line 10 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl5Lhu-OyHiu21-eD_:-Lh2pAfi12OghF1pAGcm:b-q67km1) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/catcalls.ts#L10)):*
<details><summary><i>Previously, apersingerzaius (Alex Persinger) wrote…</i></summary><blockquote>

One of the main reasons we want to attempt to extend the `routes` class is because of this line right here. We don't want to create a new connection with each call to the API per route. Ideally we only create a single connection and use that connection to the repo. This also ensures data integrity and consistency when writing and updating the state on the front end. 
</blockquote></details>

Makes sense. I'm a little confused as to how this new definition is any different however. It looks like it is still dependent on creating a connection point to all entities. Is it because it is in the app.ts class that renders the connection only once at the time of export? 
___
*[src/routes/hardwareReferenceRoutes.ts, line 15 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-LflYOlJExsa8hq1nu2f:-Lh2pe-fC7Hv3Xwsmmg8:bi75ib2) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/routes/hardwareReferenceRoutes.ts#L15)):*
<details><summary><i>Previously, apersingerzaius (Alex Persinger) wrote…</i></summary><blockquote>

Please rename `phs` to something related the class. 
</blockquote></details>

lmao thought this was some coding standard for outputs, so I used it everywhere. Now connecting the dots and realizing it means product headers.

**Review by persinac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: all files reviewed, 3 unresolved discussions (waiting on @mikecokingtin)

___
*[src/routes/catcalls.ts, line 10 at r1](https://reviewable.io/reviews/persinac/wrfserver/4#-Lfl5Lhu-OyHiu21-eD_:-Lh3If90DBmzy1o0XLAu:bhgvbzj) ([raw file](https://github.com/persinac/wrfserver/blob/324e48e225e0fc6211cbec706222663d9e703264/src/routes/catcalls.ts#L10)):*
<details><summary><i>Previously, mikecokingtin wrote…</i></summary><blockquote>

Makes sense. I'm a little confused as to how this new definition is any different however. It looks like it is still dependent on creating a connection point to all entities. Is it because it is in the app.ts class that renders the connection only once at the time of export? 
</blockquote></details>

Yes: `app.ts class that renders the connection only once at the time of export`. Then we just pass the connection to the parent class and down to the children.

**Review by persinac — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: 10 of 25 files reviewed, 4 unresolved discussions (waiting on @apersingerzaius and @mikecokingtin)

___
*[src/routes/categoryRoutes.ts, line 9 at r4](https://reviewable.io/reviews/persinac/wrfserver/4#-Lh3JiufDHEOlMAMpNTO:-Lh3JiufDHEOlMAMpNTP:bbjhekg) ([raw file](https://github.com/persinac/wrfserver/blob/f51d599a5afe5814120f51bbf44e9b5fcc483f98/src/routes/categoryRoutes.ts#L9)):*
> ```XML
> export class CategoryRoutes {
> 	public categoryRoute(app): void {
> 		createConnection().then((connection) => {
> ```

`createConnection` can disappear. Checkout how I implemented `ProductHeaderRoutes.ts` and `ProductDetailsRoutes.ts`. Each child route class must extend `Routes`, have a constructor, and implement the following methods: `setEndpoints`, `registerRoutes`.

**Review by persinac — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: 10 of 25 files reviewed, 4 unresolved discussions (waiting on @apersingerzaius and @mikecokingtin)

___
*[src/routes/hardwareReferenceRoutes.ts, line 37 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-Lh3KoGB6gEH1R9j4XFV:-Lh3KoGB6gEH1R9j4XFW:bbvui18) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/routes/hardwareReferenceRoutes.ts#L37)):*
> ```XML
>         )
>     }
> }
> ```

Remember to add a new line at the bottom of every file.

**Review by persinac — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/persinac/wrfserver/4)* status: 10 of 25 files reviewed, 5 unresolved discussions (waiting on @apersingerzaius and @mikecokingtin)

___
*[src/routes/hardwareReferenceRoutes.ts, line 11 at r3](https://reviewable.io/reviews/persinac/wrfserver/4#-Lh3KwoM5W3i6jBjbswP:-Lh3KwoM5W3i6jBjbswQ:b-c67x0b) ([raw file](https://github.com/persinac/wrfserver/blob/2935786a5362fb30eb9344adbeb8703853d1f844/src/routes/hardwareReferenceRoutes.ts#L11)):*
> ```XML
> export class HardwareReferenceRoutes {
>     public HardwareReferenceRoute(app): void {
>         createConnection().then(connection => {
> ```

Restructure as per `ProductHeaderRoutes.ts`

**Pull request closed without merging**
